feat(boom): added boom to orbos
caos/orbos pull request #164
Opened 2020-05-15 12:57 UTC by stebenz

2020-05-26 12:07 UTC, eliobischof approved these changes

2020-05-26 12:07 UTC, eliobischof commented on README.md
>  > We are currently integrating BOOM into ORBOS see our [Progress](https://github.com/caos/orbos/milestone/1)
```suggestion
```

2020-05-26 12:07 UTC, eliobischof commented on cmd/orbctl/takeoff.go
> +			}
I think it would be better separation of concerns if start.Orbiter returned the kubeconfig as byte slice?

2020-05-26 12:07 UTC, eliobischof commented on internal/git/git.go
> +
I would move this function to the package where it is used, because the cloning is a bit counter intuitive and the function is not that generic and only public methods are used

2020-05-26 12:07 UTC, eliobischof commented on internal/git/git.go
> +	}
```suggestion
```

2020-05-26 12:07 UTC, eliobischof commented on internal/operator/orbiter/destroy.go
> +func Destroy(monitor mntr.Monitor, gitClient *git.Client, adapt AdaptFunc, finishedChan chan bool) error {
inspect

2020-05-26 12:07 UTC, eliobischof commented on internal/operator/orbiter/kinds/loadbalancers/dynamic/adapt.go
> +	return func(monitor mntr.Monitor, finishedChan chan bool, desiredTree *tree.Tree, currentTree *tree.Tree) (queryFunc orbiter.QueryFunc, destroyFunc orbiter.DestroyFunc, migrate bool, err error) {
should we replace the finishedChan by context.Context?

2020-05-26 12:12 UTC, eliobischof commented on internal/operator/orbiter/destroy.go
> +func Destroy(monitor mntr.Monitor, gitClient *git.Client, adapt AdaptFunc, finishedChan chan bool) error {
i think we should replace the finishedChan by context.Context

2020-05-26 12:16 UTC, stebenz commented on cmd/orbctl/takeoff.go
> +			}
i would even go i step further and build up a list uf kubeconfigs where boom will then get deployed

2020-05-26 12:29 UTC, stebenz commented on internal/git/git.go
> +
I'll move the function to the helper package as it's just for convenience

2020-05-27 07:27 UTC, stebenz commented on internal/operator/orbiter/kinds/loadbalancers/dynamic/adapt.go
> +	return func(monitor mntr.Monitor, finishedChan chan bool, desiredTree *tree.Tree, currentTree *tree.Tree) (queryFunc orbiter.QueryFunc, destroyFunc orbiter.DestroyFunc, migrate bool, err error) {
we can replace it, but then it has to be replaced in all adaptFuncs, so i wouldn't change it

2020-05-27 09:38 UTC, eliobischof commented on internal/operator/orbiter/kinds/loadbalancers/dynamic/adapt.go
> +	return func(monitor mntr.Monitor, finishedChan chan bool, desiredTree *tree.Tree, currentTree *tree.Tree) (queryFunc orbiter.QueryFunc, destroyFunc orbiter.DestroyFunc, migrate bool, err error) {
yes, that's what i meant. i created the follow-up issue #179

2020-06-04 10:47 UTC, eliobischof commented
Writing StaticProvider secret deletes loadbalancing configuration
relates to #181

2020-06-04 11:09 UTC, stebenz commented
Bug with deleting loadbalancing configuration is corrected in #185

2020-06-04 11:50 UTC, eliobischof commented on cmd/orbctl/takeoff.go
> +			}
@stebenz why did you mark this one as resolved?

2020-06-04 11:58 UTC, stebenz commented on cmd/orbctl/takeoff.go
> +			}
as this code is outdated as per the marking and start.Orbiter() returns a list of kubeconfigs which get used for the deployment of boom

2020-06-04 13:37 UTC, eliobischof commented
![image](https://user-images.githubusercontent.com/12727842/83763578-275ecf80-a679-11ea-9b28-52e4b5208514.png)

I think the config command should log what it has done or not done

2020-06-05 08:19 UTC, eliobischof approved these changes

2020-06-05 08:19 UTC, eliobischof commented on internal/operator/orbiter/kinds/clusters/kubernetes/client.go
> +	}
```suggestion
		err := kc.Refresh(kubeconfig)
		if err != nil {
		    // do nothing
		}
```

2020-06-05 08:19 UTC, eliobischof commented on internal/operator/orbiter/kinds/clusters/kubernetes/client.go
> +	}
![image](https://user-images.githubusercontent.com/12727842/83764557-5cb7ed00-a67a-11ea-995c-1d0fc007139b.png)

2020-06-05 08:19 UTC, eliobischof commented on internal/operator/orbiter/kinds/clusters/kubernetes/client.go
> +	}
when creating a new client without having a kubeconfig, it's not an error. This behaviour is convenient because of the bootstrapping phase when no cluster exists already

2020-06-05 08:19 UTC, eliobischof commented on internal/operator/boom/application/applications/prometheus/helm.go
> +		monitor.Error(getSecretErr)
```suggestion
		monitor.Info("Not sending telemetry data to MISSION as secret grafana-cloud is missing in namespace caos-system")
```

2020-06-05 09:27 UTC, eliobischof requested changes

2020-06-05 09:27 UTC, eliobischof commented on scripts/debug.sh
> +dlv exec --api-version 2 --headless --listen 127.0.0.1:5000 /tmp/orbctldev/orbctl-Linux-x86_64 -- $@
```suggestion
dlv exec --api-version 2 --headless --listen 127.0.0.1:5000 ./artifacts/orbctl-Linux-x86_64 -- $@
```

2020-06-05 09:59 UTC, eliobischof submitted a review, later dismissed

2020-06-05 09:59 UTC, eliobischof commented on internal/operator/orbiter/kinds/clusters/kubernetes/adapt.go
> +		finishedChan <- finished
```suggestion
                go func(){
		    finishedChan <- finished
		}()
```

2020-06-05 12:20 UTC, eliobischof commented
If cloning doesn't work, we should throw it as error
![image](https://user-images.githubusercontent.com/12727842/83875570-a1ee2480-a737-11ea-84f9-f421b4e379d6.png)

2020-06-05 12:52 UTC, eliobischof commented
![image](https://user-images.githubusercontent.com/12727842/83878294-38244980-a73c-11ea-839b-d3cbb66bfaeb.png)

2020-06-05 13:10 UTC, eliobischof commented
Now, the local orbconfig is updated but not the in-cluster secret 
![image](https://user-images.githubusercontent.com/12727842/83879864-9f42fd80-a73e-11ea-9e19-b9f7bb211804.png)

2020-06-05 14:25 UTC, eliobischof approved these changes

2020-06-05 14:32 UTC, merged